import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { UserButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.post.getAll.useQuery();

  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-4">
        <UserButton />
      </div>

      <pre>{JSON.stringify(data, null, 2)}</pre>

      <div className="bg-red-500">
        {data?.map((post) => (
          <div key={post.id}>{post.content}</div>
        ))}
      </div>
    </>
  );
};

export default Home;
