import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { UserButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  // TODO: let's do this later
};

const Home: NextPage = () => {
  const { data, isLoading } = api.post.getAll.useQuery();

  console.log(data);

  if (isLoading) return <div>loading....</div>;

  if (!data) return <div>No data</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-4">
        <UserButton />
      </div>

      <main className="flex w-full justify-center  md:max-w-2xl">
        <div className="text-md flex flex-col">
          {data.map((post) => (
            <div className="border-b border-slate-200" key={post.id}>
              {post.content}
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
